export const DAY_NAMES = ["Pon", "Wto", "Śro", "Czw", "Pią", "Sob", "Nie"];
export const MONTH_NAMES = [
  "Styczeń",
  "Luty",
  "Marzec",
  "Kwiecień",
  "Maj",
  "Czerwiec",
  "Lipiec",
  "Sierpień",
  "Wrzesień",
  "Październik",
  "Listopad",
  "Grudzień",
];

export const DESCRIPTION_MAPPINGS = [
  { match: ["BIEDRONKA"], name: "Biedronka" },
  { match: ["LIDL"], name: "Lidl" },
  { match: ["KAUFLAND"], name: "Kaufland" },
  { match: ["AUCHAN"], name: "Auchan" },
  { match: ["CARREFOUR"], name: "Carrefour" },
  { match: ["NETTO"], name: "Netto" },
  { match: ["ALDI"], name: "Aldi" },
  { match: ["DINO"], name: "Dino" },
  { match: ["FAWOR"], name: "Fawor" },
  { match: ["PIEKRANIA"], name: "Piekarnia" },
  { match: ["PIEKRANIA NATURA"], name: "Natura" },
  { match: ["ZABKA", "ŻABKA"], name: "Żabka" },
  { match: ["POLOMARKET"], name: "PoloMarket" },
  { match: ["PKP INTERCITY", "PKP IC"], name: "PKP Intercity" },
  { match: ["KWIACIARNIA"], name: "Kwiaciarnia" },
  { match: ["KOLEJE MAZOWIECKIE"], name: "KM", exactWord: true },
  { match: ["KOLEJE WIELKOPOLSKIE", "KW"], name: "KW", exactWord: true },
  { match: ["POLREGIO", "PRZEWOZY REGIONALNE"], name: "PR", exactWord: true },
  { match: ["REGIOJET"], name: "RegioJet" },
  { match: ["UBER"], name: "Uber" },
  { match: ["BOLT"], name: "Bolt" },
  { match: ["FREENOW", "FREE NOW"], name: "FreeNow" },
  { match: ["JAKDOJADE"], name: "Jakdojade" },
  { match: ["SKYCASH"], name: "SkyCash" },
  { match: ["RYANAIR"], name: "Ryanair" },
  { match: ["WIZZAIR"], name: "WizzAir" },
  { match: ["ORLEN"], name: "Orlen" },
  { match: ["BP"], name: "BP", exactWord: true },
  { match: ["SHELL"], name: "Shell" },
  { match: ["CIRCLE K", "CIRCLEK"], name: "Circle K" },
  { match: ["ROSSMANN"], name: "Rossmann" },
  { match: ["SUPER-PHARM", "SUPERPHARM"], name: "Super-Pharm" },
  { match: ["HEBE"], name: "Hebe" },
  { match: ["MCDONALD", "MC DONALD"], name: "McDonald's" },
  { match: ["KFC"], name: "KFC", exactWord: true },
  { match: ["BURGER KING"], name: "Burger King" },
  { match: ["STARBUCKS"], name: "Starbucks" },
  { match: ["PYSZNE", "PYSZNE.PL"], name: "Pyszne.pl" },
  { match: ["GLOVO"], name: "Glovo" },
  { match: ["WOLT"], name: "Wolt" },
  { match: ["NETFLIX"], name: "Netflix" },
  { match: ["SPOTIFY"], name: "Spotify" },
  { match: ["APPLE.COM", "APPLE COM", "ITUNES"], name: "Apple" },
  { match: ["GOOGLE", "YOUTUBE"], name: "Google" },
  { match: ["STEAM"], name: "Steam" },
  { match: ["PLAYSTATION", "SONY"], name: "Sony" },
  { match: ["XBOX"], name: "Xbox" },
  { match: ["INEA"], name: "Inea" },
  { match: ["ALLEGRO"], name: "Allegro" },
  { match: ["AMAZON"], name: "Amazon" },
  { match: ["ALIEXPRESS"], name: "AliExpress" },
  { match: ["INPOST"], name: "InPost" },
  { match: ["IKEA"], name: "IKEA" },
  { match: ["CASTORAMA"], name: "Castorama" },
  { match: ["LEROY MERLIN"], name: "Leroy Merlin" },
  { match: ["DECATHLON"], name: "Decathlon" },
  { match: ["CCC"], name: "CCC", exactWord: true },
  { match: ["ZARA"], name: "Zara" },
  { match: ["H&M"], name: "H&M" },
  { match: ["ZALANDO"], name: "Zalando" },
  { match: ["VINTED"], name: "Vinted" },
  { match: ["PEPCO"], name: "Pepco" },
  { match: ["EMPIK"], name: "Empik" },
  { match: ["KINO MUZA"], name: "Kino Muza" },
  { match: ["CINEMA CITY"], name: "Cinema City" },
  { match: ["MULTIKINO"], name: "Multikino" },
  { match: ["HELIOS"], name: "Helios" },
  { match: ["NATIONALE-NEDERLANDEN"], name: "NN Ubezpieczenie" },
  { match: ["POZNAN ZARZAD"], name: "ZTM Poznań" }
];

export const BOILERPLATE_REGEXES = [
  /ZAKUP PRZY UŻYCIU KARTY - INTERNET/gi,
  /ZAKUP PRZY UŻYCIU KARTY W KRAJU/gi,
  /ZAKUP PRZY UŻYCIU KARTY ZA GRANICĄ/gi,
  /ZAKUP PRZY UŻYCIU KARTY/gi,
  /TRANSAKCJA KARTĄ/gi,
  /TRANSAKCJA ZBLIŻENIOWA/gi,
  /PŁATNOŚĆ KARTĄ/gi,
  /OPERACJA BLIK/gi,
  /DATA TRANSAKCJI:/gi,
  /DATA KSIĘGOWANIA:/gi,
  /KARTA:/gi,
  /PRZELEW WEWNĘTRZNY PRZYCHODZĄCY/gi,
  /PRZELEW ŚRODKÓW/gi,
  /\d{2}\.\d{2}\.\d{4}/g,
  /\d{2}-\d{3}\s+[a-zęóąśłżźćń]+/gi,
  /\d{26}/g 
];

export const REQUIRED_CATEGORIES = [
  "Opłaty stałe",
  "Rozrywka",
  "Odzież",
  "Jedzenie",
  "Elektronika",
  "Gastronomia",
  "Podróże",
  "Wakacje",
  "Inne"
];
