export const BACKPACK = [
  {
    title: "Apteczka",
    items: [
      "Plastry",
      "Plaster bezopatrunkowy – taśma",
      "Plaster bezopatrunkowy – arkusz",
      "Hydrożel",
      "Bandaż 10 cm",
      "Bandaż półelastyczny 5 cm",
      "Gazy jałowe",
      "Podpaski",
      "Koc NRC",
      "Rękawiczki",
      "Termometr",
      "Nożyczki",
      "Pilniczek",
      "Sól fizjologiczna",
      "Gaziki alkoholowe",
      "Chusteczki dekontaminacyjne",
      "Octenisept",
      "Wapno",
      "Theraflu",
      "Elektrolity",
      "Leki na gardło",
      "Leki przeciwbólowe",
      "Leki rozkurczowe",
    ],
  },
  {
    title: "Portfel",
    items: [
      "Gotówka",
      "Karty płatnicze",
      "Legitymacja",
      "Dowód osobisty",
      "PEKA",
      "EKUZ",
      "Karta biblioteczna",
      "Karty lojalnościowe",
      "Naklejki",
      "Pendrive",
      "Multitool",
      "Gumki",
      "Drut",
    ],
  },
  {
    title: "Techniczna",
    items: [
      "Multitool",
      "Miara",
      "Łyżka do butów",
      "Trytytki",
      "Siatki",
      "Grzałka",
      "Rolka do ubrań",
      "Gąbka i płyn do naczyń",
      "Sznurek i klamerki",
      "Kropelka"
    ],
  },
  {
    title: "Plecy",
    items: [
      "Laptop",
      "Notes",
      "Teczka",
      "Dokumenty",
      "Kartki, koperty, bilety",
      "Zestaw biurowy",
      "Zestaw do szycia",
      "Długopis",
      "Pisaki"
    ],
  },
  {
    title: "Mała kieszeń",
    items: [
      "Chusteczki higieniczne",
      "Chusteczki mokre",
      "Chusteczki do ekranów",
      "Nakładki na toaletę",
      "Krem",
      "Mydło",
      "Perfum",
      "Dezodorant",
      "Płyn do dezynfekcji",
      "Grzebień",
      "Zapalniczka",
      "Zatyczki do uszu",
      "Klej na gorąco",
      "Pomadka",
      "Otwieracz",
    ],
  },
  {
    title: "Elektronika",
    items: [
      "Powerbank",
      "Przewody",
      "Adapter",
      "Baterie",
    ]
  },
  {
    title: "Jedzenie",
    items: [
      "Sztućce",
      "Kawa, herbata",
      "Cukier",
      "Pieprz, sól",
      "Kisiel",
      "Guma do żucia",
    ],
  },
  {
    title: "Inne",
    items: [
      "Kubek",
      "Rzeczy",
      "Okulary",
      "Ogrzewacz do rąk",
      "Głośnik",
      "Bidon",
      "Ręcznik",
      "Rękawice",
      "Odblask",
      "Poduszka",
    ],
  },
];

export const SAFETY = [
  {
    title: "Dokumenty i pieniądze",
    items: [
      "Kserokopie dokumentów (dowód, paszport)",
      "USB z kopiami ważnych dokumentów",
      "Gotówka (małe nominały)",
      "Lista kontaktów awaryjnych",
    ],
  },
  {
    title: "Higiena i zdrowie",
    items: [
      "Apteczka pierwszej pomocy",
      "Leki na stałe (min. 3 dni)",
      "Maseczki ochronne",
      "Rękawiczki jednorazowe",
      "Chusteczki nawilżane",
      "Papier toaletowy",
      "Żel antybakteryjny",
      "Mydło"
    ],
  },
  {
    title: "Jedzenie i woda",
    items: [
      "Woda pitna",
      "Tabletki do uzdatniania wody / filtr",
      "Żywność długoterminowa",
      "Naczynia, sztućce, kubek",
      "Otwieracz do puszek",
    ],
  },
  {
    title: "Odzież",
    items: [
      "Kurtka przeciwdeszczowa",
      "Ciepła bluza / polar",
      "Bielizna",
      "Skarpetki",
      "Odzież termoaktywna",
    ],
  },
  {
    title: "Sprzęt i narzędzia",
    items: [
      "Latarka i baterie",
      "Powerbank",
      "Scyzoryk / multitool",
      "Zapałki / zapalniczka",
      "Lina / paracord",
      "Worki na śmieci",
    ],
  },
  {
    title: "Nocleg",
    items: [
      "Koc termiczny (folia NRC)",
      "Śpiwór",
      "Karimata",
    ],
  },
  {
    title: "Komunikacja i informacje",
    items: [
      "Radio na baterie",
      "Gwizdek alarmowy",
      "Notatnik i długopis",
      "Mapa lokalna",
    ],
  }
];

export const SUITCASE = [
  {
    title: "Odzież",
    items: [
      "T-shirty",
      "Koszule",
      "Sweter",
      "Bluza",
      "Spodnie długie",
      "Szorty",
      "Bielizna",
      "Skarpetki",
      "Piżama",
      "Kurtka",
      "Strój kąpielowy",
    ],
  },
  {
    title: "Obuwie",
    items: ["Buty codzienne", "Sandały", "Klapki", "Buty eleganckie"],
  },
  {
    title: "Bagaże i organizacja",
    items: ["Główna walizka", "Dodatkowe torby", "Nerka"],
  },
  {
    title: "Spanie",
    items: ["Koc podróżny", "Poduszka podróżna", "Hamak", "Śpiwór", "Karimata"],
  },
  {
    title: "Kosmetyczka",
    items: [
      "Szczoteczka do zębów",
      "Pasta do zębów",
      "Szampon / odżywka",
      "Żel pod prysznic",
      "Dezodorant",
      "Krem do twarzy",
      "Krem z filtrem",
      "Maszynka do golenia",
      "Grzebień",
      "Gumki, spinki",
    ],
  },
  {
    title: "Dokumenty i finanse",
    items: [
      "Dowód osobisty",
      "Paszport",
      "Karty płatnicze",
      "Gotówka",
      "Karta EKUZ",
      "Bilety / rezerwacje",
      "Ubezpieczenie",
    ],
  },
  {
    title: "Elektronika",
    items: [
      "Telefon",
      "Powerbank",
      "Słuchawki",
      "Aparat",
      "Ładowarki i kable",
      "Generator kodów",
      "Adapter podróżny",
      "Grzałka elektryczna ",
    ],
  },
  {
    title: "Apteczka i higiena",
    items: [
      "Leki",
      "Leki przeciwbólowe, na biegunkę, na gardło",
      "Plastry, bandaże, środki odkażające",
      "Chusteczki higieniczne",
      "Chusteczki mokre",
      "Płatki kosmetyczne",
      "Patyczki higieniczne",
      "Środek przeciw komarom/kleszczom",
    ],
  },
  {
    title: "Akcesoria i dodatki",
    items: [
      "Okulary przeciwsłoneczne",
      "Kapelusz / czapka",
      "Pasek",
      "Parasolka składana",
      "Biżuteria",
    ],
  },
  {
    title: "Rozrywka i inne",
    items: [
      "Książka",
      "Notes i długopis",
      "Gry / karty",
      "Mapa (offline)",
      "Filmy / muzyka",
    ],
  },
];